### ISSUE TITLE
Error: Leaked semaphore objects to clean up at shutdown

### ISSUE THREAD

**Issue by tarudesu** [sobamchan/engawa#1]
I'm trying to pre-train BART with your repo code, but this happened. Could you help me with this? Thank you in advance.

<img width="1215" alt="image" src="https://github.com/sobamchan/engawa/assets/76896906/c116b457-843c-4b31-9713-ac378f43a955">

**Comment by sobamchan** [comment]
Thanks for the report, I will take look in few days, and get back to you:)

**Comment by sobamchan** [comment]
Hi.

Perhaps you're trying to load data more than your RAM can hold.
Try different parameters on the following, to relax the memory usage.

- `--bs`: give smaller number for smaller batch size
- `--max-length`: give smaller number to reduce considered number of tokens
- `--model-type`: give maybe `base` to use smaller model

more details on arguments/options can be seen by running

```bash
engawa train-model --help
```

**Comment by sobamchan** [comment]
Feel free to re-open this issues if the workarounds above do not work for you.
